import type { Config } from '@react-router/dev/config';

export default {
  appDirectory: 'src',
  ssr: false,
  async prerender() {
    return [
      '/',
      '/login',
      '/portal',
      '/portal-transparansi',
      '/verifikasi-sertifikat',
      '/dashboard',
      '/settings',
      '/profile',
      '/forest',
      '/projects',
      '/project-editor',
      '/kth',
      '/transactions',
      '/upload',
      '/regulator/bursa',
      '/auditor-assignments',
      '/audit',
      '/spatial',
      '/drone',
      '/gate',
      '/audit/ptbae',
      '/audit/emission-reports',
      '/audit/forest-projects',
      '/polygon',
      '/wallet',
      '/kth/bursa',
      '/bursa',
      '/laporan',
      '/pengajuan-ptbae',
      '/kalkulator',
      '/sertifikat',
      '/dompet',
      '/ministry/applications',
      '/admin/dashboard',
      '/admin/users',
      '/admin/kyb',
    ];
  },
} satisfies Config;
