#!/usr/bin/env bash
set -euo pipefail

export HUSKY=0

RUN_ID="${1:-$GITHUB_RUN_ID}"
TARGET="${2:-all}"
BASE_BRANCH="${3:-${GITHUB_REF_NAME:-main}}"
REPO="${GITHUB_REPOSITORY:-}"

BRANCH_NAME="autofix/security-patches-${RUN_ID}"
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git checkout -B "$BRANCH_NAME"
git add -A
git commit --no-verify -m "fix(security): dynamic automated vulnerability remediation" || echo "No changes to commit"
git push --force origin "$BRANCH_NAME"

BODY=$(cat <<EOF
🤖 **Automated Security Patch Generated via Universal Auto-Fix**

This pull request was dynamically generated by the [Automated Security Remediation](https://github.com/${REPO}/actions/runs/${RUN_ID}) workflow.

### Target: \`${TARGET}\`
- Dynamically extracted and upgraded vulnerable packages.
- Regenerated lockfiles and verified tests.

*Triggered on mobile / ChatOps without requiring manual laptop intervention.*
EOF
)

echo "Creating pull request with base branch: $BASE_BRANCH..."
if PR_URL=$(gh pr create \
  --repo "$REPO" \
  --title "fix(security): automated dependency vulnerability remediation" \
  --body "$BODY" \
  --base "$BASE_BRANCH" \
  --head "$BRANCH_NAME"); then
  echo "Pull Request successfully created: $PR_URL"
else
  echo "gh pr create exited with error. Checking if PR already exists..."
  PR_URL=$(gh pr view "$BRANCH_NAME" --repo "$REPO" --json url --jq .url || true)
  if [ -n "$PR_URL" ]; then
    echo "Found existing Pull Request: $PR_URL"
  else
    echo "Error: Failed to create Pull Request and no existing PR was found."
    exit 1
  fi
fi

if [ -n "${GITHUB_ENV:-}" ]; then
  echo "PR_URL=$PR_URL" >> "$GITHUB_ENV"
fi

if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
  echo "## 🚀 Auto-Fix Pull Request Created" >> "$GITHUB_STEP_SUMMARY"
  echo "Successfully created Pull Request: [$PR_URL]($PR_URL)" >> "$GITHUB_STEP_SUMMARY"
fi
