#!/usr/bin/env bash
set -euo pipefail

RUN_ID="${1:-$GITHUB_RUN_ID}"
TARGET="${2:-all}"
REPO="${GITHUB_REPOSITORY:-}"

BRANCH_NAME="autofix/security-patches-${RUN_ID}"
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git checkout -b "$BRANCH_NAME"
git add -A
git commit -m "fix(security): dynamic automated vulnerability remediation"
git push origin "$BRANCH_NAME"

BODY=$(cat <<EOF
🤖 **Automated Security Patch Generated via Universal Auto-Fix**

This pull request was dynamically generated by the [Automated Security Remediation](https://github.com/${REPO}/actions/runs/${RUN_ID}) workflow.

### Target: \`${TARGET}\`
- Dynamically extracted and upgraded vulnerable packages.
- Regenerated lockfiles and verified tests.

*Triggered on mobile / ChatOps without requiring manual laptop intervention.*
EOF
)

PR_URL=$(gh pr create \
  --title "fix(security): automated dependency vulnerability remediation" \
  --body "$BODY" \
  --base main \
  --head "$BRANCH_NAME")

if [ -n "${GITHUB_ENV:-}" ]; then
  echo "PR_URL=$PR_URL" >> "$GITHUB_ENV"
fi

if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
  echo "## 🚀 Auto-Fix Pull Request Created" >> "$GITHUB_STEP_SUMMARY"
  echo "Successfully created Pull Request: [$PR_URL]($PR_URL)" >> "$GITHUB_STEP_SUMMARY"
fi
