packages:
  - 'client'
  - 'server'
  - 'blockchain'
allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  bcrypt: true
  esbuild: true
  keccak: true
  prisma: true
  unrs-resolver: true
  onnxruntime-node: true
engineStrict: true
