import { describe, it, expect } from 'vitest';
import { z } from 'zod';
import { ForestProjectApiItemSchema } from '../schemas/regulator.schema';

describe('Validate User forest-projects Payload', () => {
  it('should parse all 11 items or show all validation errors', () => {
    const allUserPayload = [
      {
        id: 'b9af5c02-a92b-4b50-bae2-a182c5851915',
        projectName: 'Proyek rebo isasi',
        region: 'Jawab',
        ecosystemType: 'mangrove blue carbon',
        coordinates: [-7.491348250000001, 110.01512824999999],
        polygonCoords: [
          {
            lat: -7.495,
            lng: 110.005,
          },
          {
            lat: -7.499111,
            lng: 110.013357,
          },
          {
            lat: -7.491282,
            lng: 110.022156,
          },
          {
            lat: -7.48,
            lng: 110.02,
          },
        ],
        areaHectares: 185.61,
        targetSequestrationTCO2e: 10000000,
        actualSequestrationTCO2e: 0,
        carbonStockTCO2e: 0,
        fundingBudgetIDR: 100000,
        fundingDisbursedIDR: 0,
        partnerKTH: 'KTH Mangrove Tuban Mandiri',
        kthLeader: 'Haji Supardi',
        kthMembersCount: 62,
        auditStatus: 'in_review',
        droneAuditCount: 0,
        lastDroneAuditDate: '',
        speMinted: false,
        ndviScore: 0.75,
        eviScore: 0.6,
        progressDetail: {
          survivalRatePercent: 85,
          canopyHeightMeters: 1.5,
          bufferAllocatedPercent: 8,
          bufferUsedPercent: 0,
          reforestationStatusText: 'DRAFT',
          reforestationPartner: 'KTH Mangrove Tuban Mandiri',
          reforestationSite: 'Jawab',
          targetTrees: 0,
          plantedTrees: 0,
          remainingTrees: 0,
          carbonPricePerTonIDR: 260000,
          totalBudgetIDR: 100000,
          disbursedBudgetIDR: 0,
          remainingBudgetIDR: 100000,
          currentYear: 1,
          stages: [],
          disbursements: [],
          tokenBuyers: [],
        },
        forestHealthPercent: 75,
        assignedAuditor: {
          id: '48b333b3-dd2b-48ca-8fe4-79793521738b',
          email: 'auditor@sucofindo.co.id',
          fullName: 'Dr. Ir. Rian Hermawan (PT Sucofindo Verifier)',
        },
        auditorAssignedAt: '2026-09-08T23:27:56.692Z',
        auditedAt: null,
        inspectionTimeline: [
          {
            id: '7452488c-8982-4fa5-930a-b205d7b0eb06',
            sequenceNo: 1,
            title: 'Pemantauan tahap 1',
            scheduledAt: '2026-12-07T17:00:00.000Z',
            submissionDeadline: '2026-12-21T17:00:00.000Z',
            method: 'drone',
            instructions:
              'Periksa pertumbuhan awal, tutupan tanaman, dan dokumentasi drone pada area proyek.',
            status: 'scheduled',
            indicators: [
              {
                id: '316ab59e-a03f-41e4-a655-54f220887ba0',
                code: 'CANOPY_COVER',
                label: 'Tutupan tajuk minimum (%)',
                targetValue: 70,
                unit: '%',
              },
              {
                id: '1d8733e4-e8a5-483d-9014-95b798dc0d1a',
                code: 'SURVIVAL_RATE',
                label: 'Tingkat kelangsungan hidup minimum (%)',
                targetValue: 80,
                unit: '%',
              },
            ],
            latestSubmission: null,
          },
        ],
      },
      {
        id: '8e87fa90-7c29-4717-aa94-1bf87b0dd554',
        projectName: 'asacsac',
        region: 'ascasca',
        ecosystemType: 'mangrove blue carbon',
        coordinates: [-7.489529, 110.016652],
        polygonCoords: [
          {
            lat: -7.495,
            lng: 110.005,
          },
          {
            lat: -7.494345,
            lng: 110.017521,
          },
          {
            lat: -7.488771,
            lng: 110.024087,
          },
          {
            lat: -7.48,
            lng: 110.02,
          },
        ],
        areaHectares: 158.18,
        targetSequestrationTCO2e: 100000000,
        actualSequestrationTCO2e: 0,
        carbonStockTCO2e: 0,
        fundingBudgetIDR: 1000000,
        fundingDisbursedIDR: 0,
        partnerKTH: 'KTH Mangrove Tuban Mandiri',
        kthLeader: 'Haji Supardi',
        kthMembersCount: 62,
        auditStatus: 'in_review',
        droneAuditCount: 0,
        lastDroneAuditDate: '',
        speMinted: false,
        ndviScore: 0.75,
        eviScore: 0.6,
        progressDetail: {
          survivalRatePercent: 85,
          canopyHeightMeters: 1.5,
          bufferAllocatedPercent: 8,
          bufferUsedPercent: 0,
          reforestationStatusText: 'DRAFT',
          reforestationPartner: 'KTH Mangrove Tuban Mandiri',
          reforestationSite: 'ascasca',
          targetTrees: 0,
          plantedTrees: 0,
          remainingTrees: 0,
          carbonPricePerTonIDR: 260000,
          totalBudgetIDR: 1000000,
          disbursedBudgetIDR: 0,
          remainingBudgetIDR: 1000000,
          currentYear: 1,
          stages: [],
          disbursements: [],
          tokenBuyers: [],
        },
        forestHealthPercent: 75,
        assignedAuditor: {
          id: '48b333b3-dd2b-48ca-8fe4-79793521738b',
          email: 'auditor@sucofindo.co.id',
          fullName: 'Dr. Ir. Rian Hermawan (PT Sucofindo Verifier)',
        },
        auditorAssignedAt: '2026-09-08T19:31:56.279Z',
        auditedAt: null,
        inspectionTimeline: [
          {
            id: 'd90b4348-8f4e-457e-8404-8fcce0ee3c02',
            sequenceNo: 1,
            title: 'Pemantauan tahap 1',
            scheduledAt: '2026-12-07T17:00:00.000Z',
            submissionDeadline: '2026-12-21T17:00:00.000Z',
            method: 'drone',
            instructions:
              'Periksa pertumbuhan awal, tutupan tanaman, dan dokumentasi drone pada area proyek.',
            status: 'scheduled',
            indicators: [
              {
                id: 'cfc666d7-dfc0-4c97-9f21-c1f9c3c4524b',
                code: 'CANOPY_COVER',
                label: 'Tutupan tajuk minimum (%)',
                targetValue: 70,
                unit: '%',
              },
              {
                id: '8bac7f41-7d53-4a76-b143-03b8e9dfc93a',
                code: 'SURVIVAL_RATE',
                label: 'Tingkat kelangsungan hidup minimum (%)',
                targetValue: 80,
                unit: '%',
              },
            ],
            latestSubmission: null,
          },
        ],
      },
      {
        id: 'b8d0bffb-aa0f-4cc0-b6ac-7b439779d121',
        projectName: 'ascas',
        region: 'adawd',
        ecosystemType: 'mangrove blue carbon',
        coordinates: [-7.48946525, 110.0145075],
        polygonCoords: [
          {
            lat: -7.495,
            lng: 110.005,
          },
          {
            lat: -7.493561,
            lng: 110.014179,
          },
          {
            lat: -7.4893,
            lng: 110.018851,
          },
          {
            lat: -7.48,
            lng: 110.02,
          },
        ],
        areaHectares: 94.69,
        targetSequestrationTCO2e: 100000,
        actualSequestrationTCO2e: 0,
        carbonStockTCO2e: 0,
        fundingBudgetIDR: 1000000,
        fundingDisbursedIDR: 0,
        partnerKTH: 'KTH Mangrove Tuban Mandiri',
        kthLeader: 'Haji Supardi',
        kthMembersCount: 62,
        auditStatus: 'in_review',
        droneAuditCount: 0,
        lastDroneAuditDate: '',
        speMinted: false,
        ndviScore: 0.75,
        eviScore: 0.6,
        progressDetail: {
          survivalRatePercent: 85,
          canopyHeightMeters: 1.5,
          bufferAllocatedPercent: 8,
          bufferUsedPercent: 0,
          reforestationStatusText: 'DRAFT',
          reforestationPartner: 'KTH Mangrove Tuban Mandiri',
          reforestationSite: 'adawd',
          targetTrees: 0,
          plantedTrees: 0,
          remainingTrees: 0,
          carbonPricePerTonIDR: 260000,
          totalBudgetIDR: 1000000,
          disbursedBudgetIDR: 0,
          remainingBudgetIDR: 1000000,
          currentYear: 1,
          stages: [],
          disbursements: [],
          tokenBuyers: [],
        },
        forestHealthPercent: 75,
        assignedAuditor: {
          id: '48b333b3-dd2b-48ca-8fe4-79793521738b',
          email: 'auditor@sucofindo.co.id',
          fullName: 'Dr. Ir. Rian Hermawan (PT Sucofindo Verifier)',
        },
        auditorAssignedAt: '2026-09-08T18:12:50.470Z',
        auditedAt: null,
        inspectionTimeline: [
          {
            id: 'a024f083-2793-4df3-9ca6-0327a58ff8d5',
            sequenceNo: 1,
            title: 'Pemantauan tahap 1',
            scheduledAt: '2026-12-07T17:00:00.000Z',
            submissionDeadline: '2026-12-21T17:00:00.000Z',
            method: 'drone',
            instructions:
              'Periksa pertumbuhan awal, tutupan tanaman, dan dokumentasi drone pada area proyek.',
            status: 'scheduled',
            indicators: [
              {
                id: '91f45fe7-a9f9-4f4c-9f42-059f574037d2',
                code: 'CANOPY_COVER',
                label: 'Tutupan tajuk minimum (%)',
                targetValue: 70,
                unit: '%',
              },
              {
                id: '283d3070-4b62-49f4-88dc-bf5292079c22',
                code: 'SURVIVAL_RATE',
                label: 'Tingkat kelangsungan hidup minimum (%)',
                targetValue: 80,
                unit: '%',
              },
            ],
            latestSubmission: null,
          },
        ],
      },
      {
        id: '79b05240-25e0-49ba-88b1-d6799b9a846f',
        projectName: 'ascas',
        region: 'awdadw',
        ecosystemType: 'mangrove blue carbon',
        coordinates: [-7.490794999999999, 110.014935],
        polygonCoords: [
          {
            lat: -7.495,
            lng: 110.005,
          },
          {
            lat: -7.497026,
            lng: 110.012799,
          },
          {
            lat: -7.491154,
            lng: 110.022156,
          },
          {
            lat: -7.48,
            lng: 110.02,
          },
        ],
        areaHectares: 159.64,
        targetSequestrationTCO2e: 1100000,
        actualSequestrationTCO2e: 0,
        carbonStockTCO2e: 0,
        fundingBudgetIDR: 100000,
        fundingDisbursedIDR: 0,
        partnerKTH: 'KTH Mangrove Tuban Mandiri',
        kthLeader: 'Haji Supardi',
        kthMembersCount: 62,
        auditStatus: 'in_review',
        droneAuditCount: 0,
        lastDroneAuditDate: '',
        speMinted: false,
        ndviScore: 0.75,
        eviScore: 0.6,
        progressDetail: {
          survivalRatePercent: 85,
          canopyHeightMeters: 1.5,
          bufferAllocatedPercent: 8,
          bufferUsedPercent: 0,
          reforestationStatusText: 'DRAFT',
          reforestationPartner: 'KTH Mangrove Tuban Mandiri',
          reforestationSite: 'awdadw',
          targetTrees: 0,
          plantedTrees: 0,
          remainingTrees: 0,
          carbonPricePerTonIDR: 260000,
          totalBudgetIDR: 100000,
          disbursedBudgetIDR: 0,
          remainingBudgetIDR: 100000,
          currentYear: 1,
          stages: [],
          disbursements: [],
          tokenBuyers: [],
        },
        forestHealthPercent: 75,
        assignedAuditor: {
          id: '48b333b3-dd2b-48ca-8fe4-79793521738b',
          email: 'auditor@sucofindo.co.id',
          fullName: 'Dr. Ir. Rian Hermawan (PT Sucofindo Verifier)',
        },
        auditorAssignedAt: '2026-09-08T18:11:54.792Z',
        auditedAt: null,
        inspectionTimeline: [
          {
            id: '66e8b0e2-f0e9-4f21-b9c7-9536fbbf7a96',
            sequenceNo: 1,
            title: 'Pemantauan tahap 1',
            scheduledAt: '2026-12-07T17:00:00.000Z',
            submissionDeadline: '2026-12-21T17:00:00.000Z',
            method: 'drone',
            instructions:
              'Periksa pertumbuhan awal, tutupan tanaman, dan dokumentasi drone pada area proyek.',
            status: 'scheduled',
            indicators: [
              {
                id: 'fbdf94f3-97e6-48fd-b576-817329f9b723',
                code: 'CANOPY_COVER',
                label: 'Tutupan tajuk minimum (%)',
                targetValue: 70,
                unit: '%',
              },
              {
                id: '7008138b-db1a-4155-aab4-0a0840bae0bc',
                code: 'SURVIVAL_RATE',
                label: 'Tingkat kelangsungan hidup minimum (%)',
                targetValue: 80,
                unit: '%',
              },
            ],
            latestSubmission: null,
          },
        ],
      },
      {
        id: '086b7944-4412-4f09-93b3-2e0451f67750',
        projectName: 'ascaac',
        region: 'ascasca',
        ecosystemType: 'mangrove blue carbon',
        coordinates: [-7.490412, 110.0144945],
        polygonCoords: [
          {
            lat: -7.495,
            lng: 110.005,
          },
          {
            lat: -7.495324,
            lng: 110.01121,
          },
          {
            lat: -7.491324,
            lng: 110.021768,
          },
          {
            lat: -7.48,
            lng: 110.02,
          },
        ],
        areaHectares: 137.54,
        targetSequestrationTCO2e: 10000,
        actualSequestrationTCO2e: 0,
        carbonStockTCO2e: 0,
        fundingBudgetIDR: 10000,
        fundingDisbursedIDR: 0,
        partnerKTH: 'KTH Mangrove Tuban Mandiri',
        kthLeader: 'Haji Supardi',
        kthMembersCount: 62,
        auditStatus: 'in_review',
        droneAuditCount: 0,
        lastDroneAuditDate: '',
        speMinted: false,
        ndviScore: 0.75,
        eviScore: 0.6,
        progressDetail: {
          survivalRatePercent: 85,
          canopyHeightMeters: 1.5,
          bufferAllocatedPercent: 8,
          bufferUsedPercent: 0,
          reforestationStatusText: 'DRAFT',
          reforestationPartner: 'KTH Mangrove Tuban Mandiri',
          reforestationSite: 'ascasca',
          targetTrees: 0,
          plantedTrees: 0,
          remainingTrees: 0,
          carbonPricePerTonIDR: 260000,
          totalBudgetIDR: 10000,
          disbursedBudgetIDR: 0,
          remainingBudgetIDR: 10000,
          currentYear: 1,
          stages: [],
          disbursements: [],
          tokenBuyers: [],
        },
        forestHealthPercent: 75,
        assignedAuditor: {
          id: '48b333b3-dd2b-48ca-8fe4-79793521738b',
          email: 'auditor@sucofindo.co.id',
          fullName: 'Dr. Ir. Rian Hermawan (PT Sucofindo Verifier)',
        },
        auditorAssignedAt: '2026-09-08T17:38:06.702Z',
        auditedAt: null,
        inspectionTimeline: [
          {
            id: 'd18a7e17-9526-4af5-bb07-9343dab341a3',
            sequenceNo: 1,
            title: 'Pemantauan tahap 1',
            scheduledAt: '2026-12-07T17:00:00.000Z',
            submissionDeadline: '2026-12-21T17:00:00.000Z',
            method: 'drone',
            instructions:
              'Periksa pertumbuhan awal, tutupan tanaman, dan dokumentasi drone pada area proyek.',
            status: 'scheduled',
            indicators: [
              {
                id: '9f897c93-b50c-4d5b-8a7b-71e5af5feb0b',
                code: 'CANOPY_COVER',
                label: 'Tutupan tajuk minimum (%)',
                targetValue: 70,
                unit: '%',
              },
              {
                id: 'aa84768d-de34-469f-b740-53e563035bcf',
                code: 'SURVIVAL_RATE',
                label: 'Tingkat kelangsungan hidup minimum (%)',
                targetValue: 80,
                unit: '%',
              },
            ],
            latestSubmission: null,
          },
        ],
      },
      {
        id: 'ca682af6-b077-4c3a-a0f6-b2ccd8f154bc',
        projectName: 'ggggggg',
        region: 'jawa',
        ecosystemType: 'mangrove blue carbon',
        coordinates: [-7.490263, 110.014109],
        polygonCoords: [
          {
            lat: -7.495,
            lng: 110.005,
          },
          {
            lat: -7.494655,
            lng: 110.012217,
          },
          {
            lat: -7.491397,
            lng: 110.019219,
          },
          {
            lat: -7.48,
            lng: 110.02,
          },
        ],
        areaHectares: 110.41,
        targetSequestrationTCO2e: 999999999,
        actualSequestrationTCO2e: 0,
        carbonStockTCO2e: 0,
        fundingBudgetIDR: 977777,
        fundingDisbursedIDR: 0,
        partnerKTH: 'KTH Mangrove Tuban Mandiri',
        kthLeader: 'Haji Supardi',
        kthMembersCount: 62,
        auditStatus: 'in_review',
        droneAuditCount: 0,
        lastDroneAuditDate: '',
        speMinted: false,
        ndviScore: 0.75,
        eviScore: 0.6,
        progressDetail: {
          survivalRatePercent: 85,
          canopyHeightMeters: 1.5,
          bufferAllocatedPercent: 8,
          bufferUsedPercent: 0,
          reforestationStatusText: 'DRAFT',
          reforestationPartner: 'KTH Mangrove Tuban Mandiri',
          reforestationSite: 'jawa',
          targetTrees: 0,
          plantedTrees: 0,
          remainingTrees: 0,
          carbonPricePerTonIDR: 260000,
          totalBudgetIDR: 977777,
          disbursedBudgetIDR: 0,
          remainingBudgetIDR: 977777,
          currentYear: 1,
          stages: [],
          disbursements: [],
          tokenBuyers: [],
        },
        forestHealthPercent: 75,
        assignedAuditor: {
          id: '48b333b3-dd2b-48ca-8fe4-79793521738b',
          email: 'auditor@sucofindo.co.id',
          fullName: 'Dr. Ir. Rian Hermawan (PT Sucofindo Verifier)',
        },
        auditorAssignedAt: '2026-09-08T17:32:58.827Z',
        auditedAt: null,
        inspectionTimeline: [
          {
            id: '8ef739ee-b651-46bb-983e-a8b633185dc9',
            sequenceNo: 1,
            title: 'Pemantauan tahap 1',
            scheduledAt: '2026-12-07T17:00:00.000Z',
            submissionDeadline: '2026-12-21T17:00:00.000Z',
            method: 'drone',
            instructions:
              'Periksa pertumbuhan awal, tutupan tanaman, dan dokumentasi drone pada area proyek.',
            status: 'scheduled',
            indicators: [
              {
                id: '43205c68-22b0-44c6-88f5-48742b748955',
                code: 'CANOPY_COVER',
                label: 'Tutupan tajuk minimum (%)',
                targetValue: 70,
                unit: '%',
              },
              {
                id: '366690e7-f41c-45a5-961f-d684c1800bb5',
                code: 'SURVIVAL_RATE',
                label: 'Tingkat kelangsungan hidup minimum (%)',
                targetValue: 80,
                unit: '%',
              },
            ],
            latestSubmission: null,
          },
        ],
      },
      {
        id: '8837cd47-b0a0-4e9b-89e5-ebf485703bef',
        projectName: 'ccfgctyy',
        region: 'haawaw',
        ecosystemType: 'tropical rainforest',
        coordinates: [-7.4929742500000005, 110.01688349999999],
        polygonCoords: [
          {
            lat: -7.495,
            lng: 110.005,
          },
          {
            lat: -7.503287,
            lng: 110.018588,
          },
          {
            lat: -7.49361,
            lng: 110.023946,
          },
          {
            lat: -7.48,
            lng: 110.02,
          },
        ],
        areaHectares: 268.92,
        targetSequestrationTCO2e: 447777,
        actualSequestrationTCO2e: 0,
        carbonStockTCO2e: 0,
        fundingBudgetIDR: 9999999,
        fundingDisbursedIDR: 0,
        partnerKTH: 'KTH Mangrove Tuban Mandiri',
        kthLeader: 'Haji Supardi',
        kthMembersCount: 62,
        auditStatus: 'in_review',
        droneAuditCount: 0,
        lastDroneAuditDate: '',
        speMinted: false,
        ndviScore: 0.75,
        eviScore: 0.6,
        progressDetail: {
          survivalRatePercent: 85,
          canopyHeightMeters: 1.5,
          bufferAllocatedPercent: 8,
          bufferUsedPercent: 0,
          reforestationStatusText: 'DRAFT',
          reforestationPartner: 'KTH Mangrove Tuban Mandiri',
          reforestationSite: 'haawaw',
          targetTrees: 0,
          plantedTrees: 0,
          remainingTrees: 0,
          carbonPricePerTonIDR: 260000,
          totalBudgetIDR: 9999999,
          disbursedBudgetIDR: 0,
          remainingBudgetIDR: 9999999,
          currentYear: 1,
          stages: [],
          disbursements: [],
          tokenBuyers: [],
        },
        forestHealthPercent: 75,
        assignedAuditor: {
          id: '48b333b3-dd2b-48ca-8fe4-79793521738b',
          email: 'auditor@sucofindo.co.id',
          fullName: 'Dr. Ir. Rian Hermawan (PT Sucofindo Verifier)',
        },
        auditorAssignedAt: '2026-09-08T17:30:55.634Z',
        auditedAt: null,
        inspectionTimeline: [
          {
            id: 'd5a10b79-b3e1-4a84-946d-5d85ffdcc473',
            sequenceNo: 1,
            title: 'Pemantauan tahap 1',
            scheduledAt: '2026-12-07T17:00:00.000Z',
            submissionDeadline: '2026-12-21T17:00:00.000Z',
            method: 'drone',
            instructions:
              'Periksa pertumbuhan awal, tutupan tanaman, dan dokumentasi drone pada area proyek.',
            status: 'scheduled',
            indicators: [
              {
                id: 'a6a18c3e-ae94-468f-89d4-7b2ddeb4d994',
                code: 'CANOPY_COVER',
                label: 'Tutupan tajuk minimum (%)',
                targetValue: 70,
                unit: '%',
              },
              {
                id: 'ce1223da-8488-47fd-b3ec-4771c337ec4f',
                code: 'SURVIVAL_RATE',
                label: 'Tingkat kelangsungan hidup minimum (%)',
                targetValue: 80,
                unit: '%',
              },
            ],
            latestSubmission: null,
          },
        ],
      },
      {
        id: 'b66a8fde-a1ff-4e7f-88c7-3b4054f18d66',
        projectName: 'nbh',
        region: 'jawa',
        ecosystemType: 'mangrove blue carbon',
        coordinates: [-7.4913375, 110.01494575],
        polygonCoords: [
          {
            lat: -7.495,
            lng: 110.005,
          },
          {
            lat: -7.499962,
            lng: 110.012971,
          },
          {
            lat: -7.490388,
            lng: 110.021812,
          },
          {
            lat: -7.48,
            lng: 110.02,
          },
        ],
        areaHectares: 185.62,
        targetSequestrationTCO2e: 10000000,
        actualSequestrationTCO2e: 0,
        carbonStockTCO2e: 0,
        fundingBudgetIDR: 10000000000,
        fundingDisbursedIDR: 0,
        partnerKTH: 'KTH Mangrove Tuban Mandiri',
        kthLeader: 'Haji Supardi',
        kthMembersCount: 62,
        auditStatus: 'in_review',
        droneAuditCount: 0,
        lastDroneAuditDate: '',
        speMinted: false,
        ndviScore: 0.75,
        eviScore: 0.6,
        progressDetail: {
          survivalRatePercent: 85,
          canopyHeightMeters: 1.5,
          bufferAllocatedPercent: 8,
          bufferUsedPercent: 0,
          reforestationStatusText: 'DRAFT',
          reforestationPartner: 'KTH Mangrove Tuban Mandiri',
          reforestationSite: 'jawa',
          targetTrees: 0,
          plantedTrees: 0,
          remainingTrees: 0,
          carbonPricePerTonIDR: 260000,
          totalBudgetIDR: 10000000000,
          disbursedBudgetIDR: 0,
          remainingBudgetIDR: 10000000000,
          currentYear: 1,
          stages: [],
          disbursements: [],
          tokenBuyers: [],
        },
        forestHealthPercent: 75,
        assignedAuditor: {
          id: '48b333b3-dd2b-48ca-8fe4-79793521738b',
          email: 'auditor@sucofindo.co.id',
          fullName: 'Dr. Ir. Rian Hermawan (PT Sucofindo Verifier)',
        },
        auditorAssignedAt: '2026-09-08T17:28:27.867Z',
        auditedAt: null,
        inspectionTimeline: [
          {
            id: '4cd442ba-c96c-4443-af3d-a5a486f2f59f',
            sequenceNo: 1,
            title: 'Pemantauan tahap 1',
            scheduledAt: '2026-12-07T17:00:00.000Z',
            submissionDeadline: '2026-12-21T17:00:00.000Z',
            method: 'drone',
            instructions:
              'Periksa pertumbuhan awal, tutupan tanaman, dan dokumentasi drone pada area proyek.',
            status: 'scheduled',
            indicators: [
              {
                id: '6ff236a6-21ee-4621-8eb5-7745640213ad',
                code: 'CANOPY_COVER',
                label: 'Tutupan tajuk minimum (%)',
                targetValue: 70,
                unit: '%',
              },
              {
                id: 'e5706af6-870b-4903-ab1d-5e58e883125b',
                code: 'SURVIVAL_RATE',
                label: 'Tingkat kelangsungan hidup minimum (%)',
                targetValue: 80,
                unit: '%',
              },
            ],
            latestSubmission: null,
          },
        ],
      },
      {
        id: '44938fc9-259a-4818-a0fe-78dbaf5cdd51',
        projectName: 'acasc',
        region: 'asca',
        ecosystemType: 'mangrove blue carbon',
        coordinates: [-7.4906355, 110.01436625],
        polygonCoords: [
          {
            lat: -7.495,
            lng: 110.005,
          },
          {
            lat: -7.494856,
            lng: 110.011683,
          },
          {
            lat: -7.492686,
            lng: 110.020782,
          },
          {
            lat: -7.48,
            lng: 110.02,
          },
        ],
        areaHectares: 131.76,
        targetSequestrationTCO2e: 100000000,
        actualSequestrationTCO2e: 0,
        carbonStockTCO2e: 0,
        fundingBudgetIDR: 10000000,
        fundingDisbursedIDR: 0,
        partnerKTH: 'KTH Mangrove Tuban Mandiri',
        kthLeader: 'Haji Supardi',
        kthMembersCount: 62,
        auditStatus: 'in_review',
        droneAuditCount: 0,
        lastDroneAuditDate: '',
        speMinted: false,
        ndviScore: 0.75,
        eviScore: 0.6,
        progressDetail: {
          survivalRatePercent: 85,
          canopyHeightMeters: 1.5,
          bufferAllocatedPercent: 8,
          bufferUsedPercent: 0,
          reforestationStatusText: 'DRAFT',
          reforestationPartner: 'KTH Mangrove Tuban Mandiri',
          reforestationSite: 'asca',
          targetTrees: 0,
          plantedTrees: 0,
          remainingTrees: 0,
          carbonPricePerTonIDR: 260000,
          totalBudgetIDR: 10000000,
          disbursedBudgetIDR: 0,
          remainingBudgetIDR: 10000000,
          currentYear: 1,
          stages: [],
          disbursements: [],
          tokenBuyers: [],
        },
        forestHealthPercent: 75,
        assignedAuditor: {
          id: '48b333b3-dd2b-48ca-8fe4-79793521738b',
          email: 'auditor@sucofindo.co.id',
          fullName: 'Dr. Ir. Rian Hermawan (PT Sucofindo Verifier)',
        },
        auditorAssignedAt: '2026-09-08T17:27:24.283Z',
        auditedAt: null,
        inspectionTimeline: [
          {
            id: 'f8527594-4178-4afb-ba36-e29f63e2d1bb',
            sequenceNo: 1,
            title: 'Pemantauan tahap 1',
            scheduledAt: '2026-12-07T17:00:00.000Z',
            submissionDeadline: '2026-12-21T17:00:00.000Z',
            method: 'drone',
            instructions:
              'Periksa pertumbuhan awal, tutupan tanaman, dan dokumentasi drone pada area proyek.',
            status: 'scheduled',
            indicators: [
              {
                id: 'a8d18f71-4740-4951-b2d1-4ee0ec3bdd64',
                code: 'CANOPY_COVER',
                label: 'Tutupan tajuk minimum (%)',
                targetValue: 70,
                unit: '%',
              },
              {
                id: '1e343ba3-bc3e-41a0-b080-01cfa802f5b1',
                code: 'SURVIVAL_RATE',
                label: 'Tingkat kelangsungan hidup minimum (%)',
                targetValue: 80,
                unit: '%',
              },
            ],
            latestSubmission: null,
          },
        ],
      },
      {
        id: '2a2cd728-e2d0-4b08-b6dd-b42bcb2787f1',
        projectName: 'acasc',
        region: 'asca',
        ecosystemType: 'mangrove blue carbon',
        coordinates: [-7.4875, 110.01249999999999],
        polygonCoords: [
          {
            lat: -7.495,
            lng: 110.005,
          },
          {
            lat: -7.49,
            lng: 110.01,
          },
          {
            lat: -7.485,
            lng: 110.015,
          },
          {
            lat: -7.48,
            lng: 110.02,
          },
        ],
        areaHectares: 0,
        targetSequestrationTCO2e: 100000000,
        actualSequestrationTCO2e: 0,
        carbonStockTCO2e: 0,
        fundingBudgetIDR: 10000000,
        fundingDisbursedIDR: 0,
        partnerKTH: 'KTH Mangrove Tuban Mandiri',
        kthLeader: 'Haji Supardi',
        kthMembersCount: 62,
        auditStatus: 'in_review',
        droneAuditCount: 0,
        lastDroneAuditDate: '',
        speMinted: false,
        ndviScore: 0.75,
        eviScore: 0.6,
        progressDetail: {
          survivalRatePercent: 85,
          canopyHeightMeters: 1.5,
          bufferAllocatedPercent: 8,
          bufferUsedPercent: 0,
          reforestationStatusText: 'DRAFT',
          reforestationPartner: 'KTH Mangrove Tuban Mandiri',
          reforestationSite: 'asca',
          targetTrees: 0,
          plantedTrees: 0,
          remainingTrees: 0,
          carbonPricePerTonIDR: 260000,
          totalBudgetIDR: 10000000,
          disbursedBudgetIDR: 0,
          remainingBudgetIDR: 10000000,
          currentYear: 1,
          stages: [],
          disbursements: [],
          tokenBuyers: [],
        },
        forestHealthPercent: 75,
        assignedAuditor: {
          id: '48b333b3-dd2b-48ca-8fe4-79793521738b',
          email: 'auditor@sucofindo.co.id',
          fullName: 'Dr. Ir. Rian Hermawan (PT Sucofindo Verifier)',
        },
        auditorAssignedAt: '2026-09-08T17:27:01.557Z',
        auditedAt: null,
        inspectionTimeline: [
          {
            id: '874bbac8-a1af-47f7-b326-1dff65fc4ae4',
            sequenceNo: 1,
            title: 'Pemantauan tahap 1',
            scheduledAt: '2026-12-07T17:00:00.000Z',
            submissionDeadline: '2026-12-21T17:00:00.000Z',
            method: 'drone',
            instructions:
              'Periksa pertumbuhan awal, tutupan tanaman, dan dokumentasi drone pada area proyek.',
            status: 'scheduled',
            indicators: [
              {
                id: '3f233fe3-d43c-41ac-b3b4-718892d1e531',
                code: 'CANOPY_COVER',
                label: 'Tutupan tajuk minimum (%)',
                targetValue: 70,
                unit: '%',
              },
              {
                id: 'b8b18479-fade-4d6c-9f52-7b5d7afe4369',
                code: 'SURVIVAL_RATE',
                label: 'Tingkat kelangsungan hidup minimum (%)',
                targetValue: 80,
                unit: '%',
              },
            ],
            latestSubmission: null,
          },
        ],
      },
      {
        id: '99333959-d508-4447-87ef-604bfdcd0614',
        projectName: 'Restorasi Mangrove Hutan Lindung Tuban',
        region: 'Jawa Timur',
        ecosystemType: 'mangrove blue carbon',
        coordinates: [-6.8854, 112.0123],
        polygonCoords: [
          {
            lat: -6.87,
            lng: 111.98,
          },
          {
            lat: -6.86,
            lng: 112.05,
          },
          {
            lat: -6.9,
            lng: 112.08,
          },
          {
            lat: -6.93,
            lng: 112.03,
          },
          {
            lat: -6.92,
            lng: 111.96,
          },
          {
            lat: -6.88,
            lng: 111.95,
          },
        ],
        areaHectares: 12000,
        targetSequestrationTCO2e: 980000,
        actualSequestrationTCO2e: 860000,
        carbonStockTCO2e: 860000,
        fundingBudgetIDR: 3500000000,
        fundingDisbursedIDR: 2800000000,
        partnerKTH: 'KTH Mangrove Tuban Mandiri',
        kthLeader: 'Haji Supardi',
        kthMembersCount: 62,
        auditStatus: 'in_review',
        droneAuditCount: 0,
        lastDroneAuditDate: '',
        speCertificateId: 'SPE-TUBAN-2026-001',
        speMinted: true,
        speTokenId: '2',
        speMintTxHash: '0x9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b',
        speAvailableVolumeTCO2e: 0,
        ndviScore: 0.82,
        eviScore: 0.68,
        progressDetail: {
          survivalRatePercent: 91.2,
          canopyHeightMeters: 2.1,
          bufferAllocatedPercent: 8,
          bufferUsedPercent: 0,
          reforestationStatusText: 'ACTIVE_DMRV',
          reforestationPartner: 'KTH Mangrove Tuban Mandiri',
          reforestationSite: 'Jawa Timur',
          targetTrees: 50000,
          plantedTrees: 50000,
          remainingTrees: 0,
          carbonPricePerTonIDR: 650000,
          totalBudgetIDR: 3500000000,
          disbursedBudgetIDR: 2800000000,
          remainingBudgetIDR: 700000000,
          currentYear: 1,
          stages: [
            {
              year: 1,
              title: 'Tahun 1: Pembibitan Mangrove Rhizophora',
              milestone: 'Penanaman 50.000 bibit mangrove dan pembangunan tanggul penahan ombak.',
              status: 'completed',
              canopyDensity: 55,
              gsd: 2.5,
              kthName: 'KTH Mangrove Tuban Mandiri',
              farmerIncentiveIDR: 300000000,
              incentiveStatus: 'Telah Disalurkan',
              speCreditMinted: 0,
              speStatus: 'Terbit',
              plantedTrees: 50000,
              targetTrees: 50000,
              remainingTrees: 0,
            },
          ],
          disbursements: [
            {
              id: '383120fc-14d3-4119-9dea-cc68f88dc61b',
              date: '2025-07-14',
              amountIDR: 45000000,
              category: 'Pemeliharaan',
              desc: 'Insentif bulanan KTH (Dinas Kehutanan Jawa Timur & KTH Tuban)',
              txHash: '0x8f3a9b2c1d4e7f0a5b6c7d8e9f0a1b2c',
              blockNumber: '#184920',
              vendor: 'Dinas Kehutanan Jawa Timur & KTH Tuban',
              status: 'DISBURSED',
              items: [
                {
                  name: 'Insentif Tanam & Pemeliharaan KTH (15 Anggota)',
                  qty: 15,
                  unit: 'Anggota',
                  priceIDR: 2000000,
                  totalIDR: 30000000,
                },
                {
                  name: 'Pengadaan Pupuk Kompos Organik Bio-Fertilizer',
                  qty: 30,
                  unit: 'Karung',
                  priceIDR: 300000,
                  totalIDR: 9000000,
                },
                {
                  name: 'Operasional Alat Penyiangan & Pemangkasan',
                  qty: 6,
                  unit: 'Set',
                  priceIDR: 1000000,
                  totalIDR: 6000000,
                },
              ],
              proofImages: [
                '/proofs/nota_pembelian.svg',
                '/proofs/bukti_transfer.svg',
                '/proofs/sertifikat_spe.svg',
              ],
            },
            {
              id: '9d9750f4-029b-4fd4-aee0-f4cd81d01591',
              date: '2025-06-28',
              amountIDR: 85000000,
              category: 'Monitoring',
              desc: 'Sewa UAV & pemindaian orthophoto udara dMRV',
              txHash: '0x3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a',
              blockNumber: '#183712',
              vendor: 'PT Aero Mapping Indonesia',
              status: 'DISBURSED',
              items: [
                {
                  name: 'Sewa Drone VTOL LiDAR Multiterrain (3 Hari)',
                  qty: 3,
                  unit: 'Hari',
                  priceIDR: 20000000,
                  totalIDR: 60000000,
                },
                {
                  name: 'Jasa Pengolahan Citra dMRV & Model CHM',
                  qty: 1,
                  unit: 'Paket',
                  priceIDR: 15000000,
                  totalIDR: 15000000,
                },
                {
                  name: 'Honor Pilot Drone Sertifikasi FASI & Surveyor',
                  qty: 2,
                  unit: 'Orang',
                  priceIDR: 5000000,
                  totalIDR: 10000000,
                },
              ],
              proofImages: [
                '/proofs/nota_pembelian.svg',
                '/proofs/bukti_transfer.svg',
                '/proofs/sertifikat_spe.svg',
              ],
            },
          ],
          tokenBuyers: [
            {
              id: '83313181-2a63-4b5f-9db7-9935f7c34d49',
              companyName: 'PT Semen Nusantara Tuban',
              sector: 'Industri Semen & Manufaktur Klinker',
              tCO2e: 50000,
              amountIDR: 13000000000,
              date: '2025-07-10',
              speCertificateId: 'SPE-TUBAN-2026-001',
              txHash: '0x9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d',
            },
            {
              id: '5ff0e289-e93c-49d8-b15e-261857947fac',
              companyName: 'Singapore Regional Green Fund',
              sector: 'Industri Karbon',
              tCO2e: 20000,
              amountIDR: 5200000000,
              date: '2025-07-05',
              speCertificateId: 'SPE-TUBAN-2026-001',
              txHash: '0x4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a',
            },
          ],
        },
        forestHealthPercent: 82,
        assignedAuditor: null,
        auditorAssignedAt: null,
        auditedAt: null,
        inspectionTimeline: [],
      },
      {
        id: 'bb77686f-45e9-44ba-947d-8ae6e4da142a',
        projectName: 'Taman Nasional Baluran Canopy Restoration',
        region: 'Jawa Timur',
        ecosystemType: 'tropical rainforest',
        coordinates: [-7.8385, 114.3725],
        polygonCoords: [
          {
            lat: -7.732,
            lng: 114.398,
          },
          {
            lat: -7.735,
            lng: 114.471,
          },
          {
            lat: -7.822,
            lng: 114.478,
          },
          {
            lat: -7.889,
            lng: 114.452,
          },
          {
            lat: -7.911,
            lng: 114.331,
          },
          {
            lat: -7.832,
            lng: 114.288,
          },
          {
            lat: -7.748,
            lng: 114.321,
          },
        ],
        areaHectares: 25000,
        targetSequestrationTCO2e: 1500000,
        actualSequestrationTCO2e: 1240000,
        carbonStockTCO2e: 1240000,
        fundingBudgetIDR: 4850000000,
        fundingDisbursedIDR: 3750000000,
        partnerKTH: 'KTH Rimba Baluran Lestari',
        kthLeader: 'Sutrisno, S.Hut',
        kthMembersCount: 84,
        auditStatus: 'in_review',
        droneAuditCount: 0,
        lastDroneAuditDate: '',
        speCertificateId: 'SPE-BALURAN-2026-001',
        speMinted: true,
        speTokenId: '1',
        speMintTxHash: '0x7f9a8b1c94857102948571029485710294857102948571029485710294857102',
        speAvailableVolumeTCO2e: 48750,
        ndviScore: 0.78,
        eviScore: 0.61,
        progressDetail: {
          survivalRatePercent: 87.5,
          canopyHeightMeters: 1.85,
          bufferAllocatedPercent: 8,
          bufferUsedPercent: 0,
          reforestationStatusText: 'ACTIVE_DMRV',
          reforestationPartner: 'KTH Rimba Baluran Lestari',
          reforestationSite: 'Jawa Timur',
          targetTrees: 80000,
          plantedTrees: 78500,
          remainingTrees: 1500,
          carbonPricePerTonIDR: 260000,
          totalBudgetIDR: 4850000000,
          disbursedBudgetIDR: 3750000000,
          remainingBudgetIDR: 1100000000,
          currentYear: 1,
          stages: [
            {
              year: 1,
              title: 'Tahun 1: Pembibitan & Persiapan Lahan Kritis',
              milestone: 'Pengadaan 40.000 bibit endemik dan pembuatan sekat bakar.',
              status: 'completed',
              canopyDensity: 32,
              gsd: 2.5,
              kthName: 'KTH Rimba Baluran Lestari',
              farmerIncentiveIDR: 350000000,
              incentiveStatus: 'Telah Disalurkan',
              speCreditMinted: 0,
              speStatus: 'Terbit',
              plantedTrees: 40000,
              targetTrees: 40000,
              remainingTrees: 0,
            },
            {
              year: 2,
              title: 'Tahun 2: Penanaman Intensif & Monitoring IoT',
              milestone: 'Pemasangan 12 unit sensor kanopi dan verifikasi LiDAR drone.',
              status: 'ongoing',
              canopyDensity: 48.5,
              gsd: 2.5,
              kthName: 'KTH Rimba Baluran Lestari',
              farmerIncentiveIDR: 450000000,
              incentiveStatus: 'Telah Disalurkan',
              speCreditMinted: 0,
              speStatus: 'Terbit',
              plantedTrees: 38500,
              targetTrees: 40000,
              remainingTrees: 1500,
            },
          ],
          disbursements: [
            {
              id: '06f8744a-e394-4cbc-8aa9-91d6fa3bc376',
              date: '2026-01-25',
              amountIDR: 350000000,
              category: 'Restorasi & Pembibitan',
              desc: 'Pengadaan 40.000 bibit endemik dan pembuatan sekat bakar',
              txHash: '0x3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c',
              blockNumber: '#183100',
              vendor: 'KTH Baluran Mandiri',
              status: 'DISBURSED',
              items: [
                {
                  name: 'Pengadaan Bibit Pohon Endemik Baluran',
                  qty: 40000,
                  unit: 'Batang',
                  priceIDR: 7500,
                  totalIDR: 300000000,
                },
                {
                  name: 'Pembuatan Sekat Bakar & Jalur Pemadam Firebreak',
                  qty: 5,
                  unit: 'KM',
                  priceIDR: 10000000,
                  totalIDR: 50000000,
                },
              ],
              proofImages: ['/proofs/nota_pembelian.svg', '/proofs/bukti_transfer.svg'],
            },
          ],
          tokenBuyers: [
            {
              id: 'fb13ad71-9721-4a55-acf6-4c8364672a48',
              companyName: 'Singapore Regional Green Fund',
              sector: 'Industri Karbon',
              tCO2e: 1250,
              amountIDR: 325000000,
              date: '2026-02-18',
              speCertificateId: 'SPE-BALURAN-2026-001',
              txHash: '0x8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b',
            },
          ],
        },
        forestHealthPercent: 78,
        assignedAuditor: null,
        auditorAssignedAt: null,
        auditedAt: null,
        inspectionTimeline: [],
      },
    ];

    const result = z.array(ForestProjectApiItemSchema).safeParse(allUserPayload);
    if (!result.success) {
      console.log('VALIDATION ISSUES COUNT:', result.error.issues.length);
      console.log('VALIDATION ERRORS:', JSON.stringify(result.error.issues, null, 2));
    }
    expect(result.success).toBe(true);
  });
});
