-- AlterEnum
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'superadmin';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'regulator';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'auditor';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'emitter';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'kth';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'buyer';

