#!/usr/bin/env sh

# Load NVM Node 24.15.0 & PNPM for non-interactive Git subshells
export NVM_DIR="$HOME/.nvm"
if [ -s "$NVM_DIR/nvm.sh" ]; then
  . "$NVM_DIR/nvm.sh"
  nvm use 24.15.0 >/dev/null 2>&1
fi

export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"

pnpm exec lint-staged

