name: Continuous Deployment (CD)

on:
  workflow_run:
    workflows: ["Continuous Integration (CI)"]
    types:
      - completed
    branches: [ "main" ]

jobs:
  deploy-to-server:
    # Hanya berjalan jika CI (Testing) berhasil
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v3

    - name: 🔐 Connect to Tailscale Network
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ secrets.TS_AUTHKEY }}
        tags: tag:ci

    - name: 🚚 Transfer Files via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        # Memindahkakan seluruh file dari GitHub ke server folder ~/VM_BLOCKHAIN
        source: "."
        target: "~/VM_BLOCKHAIN"
        strip_components: 0
        
    - name: 🚀 Execute Deployment on Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          echo "Memasuki direktori proyek..."
          cd ~/VM_BLOCKHAIN
          
          echo "Menginstall dependensi..."
          npm ci
          
          echo "Menjalankan Docker Hyperledger Besu..."
          sudo docker-compose up -d
          
          echo "Menunggu Node Besu siap (sleep 10s)..."
          sleep 10
          
          echo "Melakukan Deployment Smart Contract ke Node Besu..."
          npx hardhat run scripts/deploy.js --network besu_local
          
          echo "✅ DEPLOYMENT SERVER SELESAI!"
